version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../.docker/backend/Dockerfile
    ports:
      - "4000:3000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: ../.docker/frontend/Dockerfile
    ports:
      - "4001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  db:
    image: postgres:15-alpine
    ports:
      - "4002:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
